# Generated by Django 4.0 on 2021-12-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('health', models.IntegerField(blank=True)),
                ('satiety', models.IntegerField(blank=True)),
                ('happiness', models.IntegerField(blank=True)),
                ('photo_url', models.ImageField(upload_to='photos/NFT', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'NFS карточки',
                'verbose_name_plural': 'NFS карточки',
            },
        ),
    ]
