# Generated by Django 4.0 on 2021-12-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectnft',
            name='price_card',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
