# Generated by Django 4.0 on 2021-12-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_selectnft_price_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectnft',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='selectnft',
            name='nft_storage_url',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
