# Generated by Django 4.0 on 2021-12-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_selectnft_photo_url_selectnft_nft_storage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectnft',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
