# Generated by Django 4.0 on 2021-12-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_selectnft_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectnft',
            name='nft_storage_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
