# Generated by Django 4.0 on 2021-12-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_selectnft_nft_storage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectnft',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='selectnft',
            name='nft_storage_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
