# Generated by Django 4.0 on 2021-12-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslist',
            options={'verbose_name': 'Новини', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterField(
            model_name='newslist',
            name='description',
            field=models.TextField(verbose_name='Текст публікації'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Публікація'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='photo_url',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
