# Generated by Django 4.0 on 2021-12-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsline', '0002_alter_newslist_options_alter_newslist_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslist',
            name='views',
            field=models.IntegerField(default=1, verbose_name='Кількість переглядів'),
            preserve_default=False,
        ),
    ]
